// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using DALQueryChain.Interfaces;
using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace ManualTest.Linq2Db.Context
{
	[Table("Products")]
	public class Product : IDbModelBase
	{
		[Column("Id"        , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int      Id         { get; set; } // integer
		[Column("Name"      , CanBeNull    = false                                                             )] public string   Name       { get; set; } = null!; // character varying(150)
		[Column("Created"                                                                                      )] public DateTime Created    { get; set; } // date
		[Column("Price"                                                                                        )] public decimal? Price      { get; set; } // numeric
		[Column("Count"                                                                                        )] public int?     Count      { get; set; } // integer
		[Column("CategoryId"                                                                                   )] public int?     CategoryId { get; set; } // integer
		[Column("Raiting"                                                                                      )] public double?  Raiting    { get; set; } // double precision

		#region Associations
		/// <summary>
		/// Products_CategoryId_fkey
		/// </summary>
		[Association(ThisKey = nameof(CategoryId), OtherKey = nameof(Context.Category.Id))]
		public Category? Category { get; set; }
		#endregion
	}
}
