// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Configuration;
using LinqToDB.Data;

#pragma warning disable 1573, 1591
#nullable enable

namespace ManualTest.Linq2Db.Context
{
	public partial class TestContext : DataConnection
	{
		#region Schemas
		public void InitSchemas()
		{
			Identity = new IdentitySchema.DataContext(this);
		}

		public IdentitySchema.DataContext Identity { get; set; } = null!;
		#endregion

		public TestContext()
		{
			InitSchemas();
			InitDataContext();
		}

		public TestContext(string configuration)
			: base(configuration)
		{
			InitSchemas();
			InitDataContext();
		}

		public TestContext(LinqToDBConnectionOptions<TestContext> options)
			: base(options)
		{
			InitSchemas();
			InitDataContext();
		}

		partial void InitDataContext();
	}
}
